platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(flutter_application_path)
  # Install Flutter engine
  flutter_podspec = File.join(flutter_application_path, '.symlinks', 'flutter', 'ios', 'Flutter.podspec')
  if File.exist?(flutter_podspec)
    pod 'Flutter', :path => File.join(flutter_application_path, '.symlinks', 'flutter', 'ios')
  end

  # Read .flutter-plugins-dependencies to find iOS plugins
  plugins_file = File.join(flutter_application_path, '..', '.flutter-plugins-dependencies')
  if File.exist?(plugins_file)
    require 'json'
    plugins_json = JSON.parse(File.read(plugins_file))
    ios_plugins = plugins_json['plugins']['ios'] || []
    ios_plugins.each do |plugin|
      plugin_name = plugin['name']
      plugin_path = File.join(flutter_application_path, '.symlinks', plugin_name, 'ios')
      if File.directory?(plugin_path)
        pod plugin_name, :path => plugin_path
      end
    end
  else
    # Fallback: scan .symlinks directory
    symlinks_dir = File.join(flutter_application_path, '.symlinks')
    if File.directory?(symlinks_dir)
      Dir.foreach(symlinks_dir) do |entry|
        next if entry.start_with?('.')
        plugin_path = File.join(symlinks_dir, entry, 'ios')
        if File.directory?(plugin_path)
          pod entry, :path => plugin_path
        end
      end
    end
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
